# -*- coding: utf-8 -*-
"""Marimo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyrTaY1jvLM18Nxp9G2tHGYlB32BuF1z
"""

!pip install marimo
import marimo as mo

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import plotly.graph_objects as go
import warnings
import marimo as mo
import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_curve
warnings.filterwarnings('ignore')

import pandas as pd

df_data_record = pd.read_csv('/Exam_Score_Prediction.csv')

df_data_record.info()

df_data_record.head(10)

print(f"In data_record.csv: {df_data_record.shape[0]} rows, {df_data_record.shape[1]} columns")

duplicates_data = df_data_record.duplicated()
num_duplicates_data = duplicates_data.sum()
print(f"For data_records.csv duplicates: {num_duplicates_data}")

print(f"In data_record.csv nulls:")
print(df_data_record.isnull().sum())

print(f"Age from {df_data_record['age'].min()} to {df_data_record['age'].max()} years old")
print(f"Study hours: from {df_data_record['study_hours'].min()} to {df_data_record['study_hours'].max()} hours")
print(f"Class attendance: from {df_data_record['class_attendance'].min()} to {df_data_record['class_attendance'].max()} percents")
print(f"Sleep hours: from {df_data_record['sleep_hours'].min()} to {df_data_record['sleep_hours'].max()} hours")

features = ["study_hours", "class_attendance", "sleep_hours"]
target = "exam_score"

X = df_data_record[features]
y = df_data_record[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

joblib.dump(model, "exam_model.pkl")